version: '3.5'

services:
  master:
    build: ./master
    container_name: master
    hostname: master
    #volumes:
    #- type: bind
    #  source: ./shared
    #  target: /root/.ssh
    tty: true
    stdin_open: true
    #command: /bin/bash
    #command: cp -r /mnt/shared/ /root/.ssh/
    entrypoint: /bin/bash
  worker1:
    build: ./worker1
    container_name: worker1
    hostname: worker1
    #volumes:
    #- type: bind
    #  source: ./shared
    #  target: /mnt/shared
    #entrypoint: [ "sh", "/etc/init.d/ssh", "start"]
    entrypoint: [ "/usr/sbin/sshd","-D" ]