version: '3.5'

services:
  master:
    build: ./master
    container_name: master
    hostname: master
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
  worker1:
    build: ./worker1
    container_name: worker1
    hostname: worker1
    entrypoint: [ "/usr/sbin/sshd","-D" ]
    depends_on:
      - master
  worker2:
    build: ./worker2
    container_name: worker2
    hostname: worker2
    entrypoint: [ "/usr/sbin/sshd","-D" ]
    depends_on:
      - master